"""
export_unity.py — Export a Manifold surface to Unity-ready formats.

Outputs
-------
  <name>.unity.json   Prefab-ready mesh descriptor Unity can load via a
                      custom importer (C# stub also emitted alongside it).
                      Format matches Unity's Mesh API fields exactly so the
                      importer is a direct array assignment, no conversion.

  <name>Importer.cs   Ready-to-drop C# MonoBehaviour that reads the JSON
                      and populates a UnityEngine.Mesh at runtime or in the
                      editor via AssetPostprocessor.

Design notes
------------
- No Unity SDK required on the Python side — pure stdlib.
- Coordinates: Unity uses left-handed Y-up.  Manifold uses right-handed
  Z-up.  This exporter applies the standard transform:
      manifold (x, y, z)  →  Unity (x, z, y)   [swap Y↔Z]
  Winding order is reversed (counter-clockwise → clockwise) to match
  Unity's front-face convention.
- Normals are transformed the same way.
- The JSON is signed with SHA-256 so the C# importer can verify integrity
  before uploading to the GPU.
"""

import json
import hashlib
import struct
from pathlib import Path
from typing import Union

from manifold_core import Manifold, ManifoldInstance
from manifold_mesh import tessellate


# ---------------------------------------------------------------------------
# Coordinate-system transform
# ---------------------------------------------------------------------------

def _to_unity(x: float, y: float, z: float) -> list[float]:
    """Right-handed Z-up → Unity left-handed Y-up."""
    return [x, z, y]


def _winding_reversed(face: list[int]) -> list[int]:
    """Reverse CCW→CW winding for Unity front-face convention."""
    return [face[0], face[2], face[1]]


# ---------------------------------------------------------------------------
# Unity prefab JSON exporter
# ---------------------------------------------------------------------------

def export_unity(
    source: Union[Manifold, ManifoldInstance],
    stem: str = "static/manifold",
    res: int = 100,
    scale: float = 1.0,
    t: float = 0.0,
) -> tuple[Path, Path]:
    """
    Write <stem>.unity.json and <stem>Importer.cs.

    The JSON matches Unity's Mesh API:
      vertices  → Mesh.vertices  (Vector3[])
      normals   → Mesh.normals   (Vector3[])
      uv        → Mesh.uv        (Vector2[])
      triangles → Mesh.triangles (int[])

    Returns
    -------
    (json_path, cs_path)
    """
    mesh = tessellate(source, res=res, scale=scale, t=t)
    name  = mesh["name"]
    attrs = mesh["attributes"]

    # Transform coordinate system
    u_verts = [_to_unity(*v) for v in mesh["vertices"]]
    u_norms = [_to_unity(*n) for n in mesh["normals"]]
    u_uvs   = [[uv[0], uv[1]] for uv in mesh["uvs"]]

    # Flatten triangles and reverse winding
    triangles: list[int] = []
    for face in mesh["faces"]:
        rf = _winding_reversed(face)
        triangles.extend(rf)

    # Build payload
    payload: dict = {
        "name":      name,
        "vertices":  u_verts,
        "normals":   u_norms,
        "uv":        u_uvs,
        "triangles": triangles,
        "attributes": attrs,
        "meta": {
            "res":   res,
            "scale": scale,
            "t":     t,
            "coord": "unity-lh-yup",
            "winding": "cw",
        },
    }

    # Sign
    payload_bytes = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode()
    payload["hash"] = hashlib.sha256(payload_bytes).hexdigest()

    json_path = Path(stem).with_suffix(".unity.json")
    json_path.parent.mkdir(parents=True, exist_ok=True)

    with json_path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, separators=(",", ":"))

    # C# importer stub
    cs_path = Path(stem).parent / f"{_pascal(name)}Importer.cs"
    _write_cs_importer(cs_path, name, json_path.name)

    vcount = len(u_verts)
    tcount = len(triangles) // 3
    print(f"Unity JSON {name!r} → {json_path}  ({vcount}v {tcount}f)")
    print(f"Unity C#   {name!r} → {cs_path}")
    return json_path, cs_path


# ---------------------------------------------------------------------------
# C# importer stub
# ---------------------------------------------------------------------------

_CS_TEMPLATE = '''\
// {pascal_name}Importer.cs — Auto-generated by Manifold Compiler
// Drop into any GameObject to load the manifold mesh at runtime.
// Requires: {json_filename} in a Resources/ folder (or adjust path below).
using System;
using System.IO;
using UnityEngine;

[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer))]
public class {pascal_name}Importer : MonoBehaviour
{{
    [Tooltip("Path inside Resources/ folder, without extension")]
    public string resourcePath = "{name}";

    void Start() => LoadMesh();

    public void LoadMesh()
    {{
        TextAsset asset = Resources.Load<TextAsset>(resourcePath);
        if (asset == null) {{ Debug.LogError($"Manifold: resource not found: {{resourcePath}}"); return; }}

        ManifoldMeshData data = JsonUtility.FromJson<ManifoldMeshData>(asset.text);

        // Integrity check
        string storedHash = data.hash;
        data.hash = null;
        string recomputed = SHA256Hex(JsonUtility.ToJson(data));
        if (recomputed != storedHash)
        {{ Debug.LogError("Manifold: hash mismatch — mesh data corrupted or tampered"); return; }}

        Mesh mesh = new Mesh {{ name = data.name, indexFormat = UnityEngine.Rendering.IndexFormat.UInt32 }};
        mesh.SetVertices(Array.ConvertAll(data.vertices, v => new Vector3(v[0], v[1], v[2])));
        mesh.SetNormals (Array.ConvertAll(data.normals,  n => new Vector3(n[0], n[1], n[2])));
        mesh.SetUVs(0, Array.ConvertAll(data.uv, u => new Vector2(u[0], u[1])));
        mesh.SetTriangles(data.triangles, 0);
        mesh.RecalculateBounds();

        GetComponent<MeshFilter>().sharedMesh = mesh;
        Debug.Log($"Manifold: loaded {{{(}data.name{)}}}, {{mesh.vertexCount}}v {{mesh.triangles.Length / 3}}f");
    }}

    static string SHA256Hex(string s)
    {{
        using var sha = System.Security.Cryptography.SHA256.Create();
        byte[] bytes = sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(s));
        return BitConverter.ToString(bytes).Replace("-", "").ToLower();
    }}

    [Serializable] class ManifoldMeshData
    {{
        public string   name;
        public float[][] vertices;
        public float[][] normals;
        public float[][] uv;
        public int[]    triangles;
        public string   hash;
    }}
}}
'''


def _write_cs_importer(path: Path, name: str, json_filename: str) -> None:
    pascal = _pascal(name)
    # Format without f-string to avoid brace conflicts in template
    cs = _CS_TEMPLATE.replace("{pascal_name}", pascal)
    cs = cs.replace("{name}", name)
    cs = cs.replace("{json_filename}", json_filename)
    # Fix the escaped log format string braces
    cs = cs.replace("{{{(}data.name{)}}}", "{data.name}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(cs, encoding="utf-8")


def _pascal(name: str) -> str:
    """Convert snake_case or kebab-case to PascalCase."""
    return "".join(w.capitalize() for w in name.replace("-", "_").split("_"))
