// GyroidImporter.cs — Auto-generated by Manifold Compiler
// Drop into any GameObject to load the manifold mesh at runtime.
// Requires: gyroid.unity.json in a Resources/ folder (or adjust path below).
using System;
using System.IO;
using UnityEngine;

[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer))]
public class GyroidImporter : MonoBehaviour
{{
    [Tooltip("Path inside Resources/ folder, without extension")]
    public string resourcePath = "gyroid";

    void Start() => LoadMesh();

    public void LoadMesh()
    {{
        TextAsset asset = Resources.Load<TextAsset>(resourcePath);
        if (asset == null) {{ Debug.LogError($"Manifold: resource not found: {{resourcePath}}"); return; }}

        ManifoldMeshData data = JsonUtility.FromJson<ManifoldMeshData>(asset.text);

        // Integrity check
        string storedHash = data.hash;
        data.hash = null;
        string recomputed = SHA256Hex(JsonUtility.ToJson(data));
        if (recomputed != storedHash)
        {{ Debug.LogError("Manifold: hash mismatch — mesh data corrupted or tampered"); return; }}

        Mesh mesh = new Mesh {{ name = data.name, indexFormat = UnityEngine.Rendering.IndexFormat.UInt32 }};
        mesh.SetVertices(Array.ConvertAll(data.vertices, v => new Vector3(v[0], v[1], v[2])));
        mesh.SetNormals (Array.ConvertAll(data.normals,  n => new Vector3(n[0], n[1], n[2])));
        mesh.SetUVs(0, Array.ConvertAll(data.uv, u => new Vector2(u[0], u[1])));
        mesh.SetTriangles(data.triangles, 0);
        mesh.RecalculateBounds();

        GetComponent<MeshFilter>().sharedMesh = mesh;
        Debug.Log($"Manifold: loaded {data.name}, {{mesh.vertexCount}}v {{mesh.triangles.Length / 3}}f");
    }}

    static string SHA256Hex(string s)
    {{
        using var sha = System.Security.Cryptography.SHA256.Create();
        byte[] bytes = sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(s));
        return BitConverter.ToString(bytes).Replace("-", "").ToLower();
    }}

    [Serializable] class ManifoldMeshData
    {{
        public string   name;
        public float[][] vertices;
        public float[][] normals;
        public float[][] uv;
        public int[]    triangles;
        public string   hash;
    }}
}}
