#!/usr/bin/env node
/**
 * 🦋 bfx-ingest — turn any codebase into clean, deterministic, AI-ready context.
 *
 *   npx bfx-ingest <folder> [--format md|xml|json] [--out FILE] [--max-kb N]
 *
 * What it does:
 *   • walks the folder (skips junk + binaries, honours a basic .gitignore)
 *   • content-addresses every file and DEDUPES identical ones (token savings)
 *   • emits ONE context artifact in the format your model likes
 *   • stamps a reproducible root hash + manifest so you can prove exactly what
 *     was sent (same repo in → same bytes + same hash out, on any machine)
 *
 * No deps. No network. Your code never leaves your machine.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const DEFAULT_SKIP_DIRS = new Set(['.git', 'node_modules', 'dist', 'build', '.next', '.cache', 'coverage', 'vendor', 'bfx-out', '.venv', '__pycache__']);
const SKIP_FILE = /\.(png|jpe?g|gif|webp|ico|svg|pdf|zip|gz|tar|rar|7z|mp4|mov|webm|mp3|wav|ogg|woff2?|ttf|eot|otf|exe|dll|so|dylib|bin|wasm|class|o|a|lib|lock|min\.js|min\.css|map)$/i;

function fnv(buf) { let h = 0x811c9dc5 >>> 0; for (let i = 0; i < buf.length; i++) { h ^= (typeof buf === 'string' ? buf.charCodeAt(i) & 0xff : buf[i]); h = Math.imul(h, 0x01000193) >>> 0; } return (h >>> 0).toString(16).padStart(8, '0'); }
const isBinary = (buf) => { const n = Math.min(buf.length, 8000); for (let i = 0; i < n; i++) if (buf[i] === 0) return true; return false; };
const estTokens = (chars) => Math.ceil(chars / 4);   // standard rough heuristic
const fence = (p) => { const e = (p.split('.').pop() || '').toLowerCase(); return ({ js: 'javascript', ts: 'typescript', jsx: 'jsx', tsx: 'tsx', py: 'python', rb: 'ruby', go: 'go', rs: 'rust', java: 'java', c: 'c', h: 'c', cpp: 'cpp', cs: 'csharp', php: 'php', sh: 'bash', json: 'json', yml: 'yaml', yaml: 'yaml', md: 'markdown', html: 'html', css: 'css', sql: 'sql' }[e] || ''); };

function loadIgnore(root) {
  const globs = [];
  try { fs.readFileSync(path.join(root, '.gitignore'), 'utf8').split(/\r?\n/).forEach(l => { l = l.trim(); if (l && !l.startsWith('#')) globs.push(l.replace(/\/$/, '')); }); } catch (_) {}
  return (rel) => globs.some(g => rel === g || rel.startsWith(g + '/') || rel.split('/').includes(g) || (g.startsWith('*.') && rel.endsWith(g.slice(1))));
}

function ingest(root, opts) {
  root = path.resolve(root);
  const ignored = loadIgnore(root);
  const maxBytes = (opts.maxKb || 256) * 1024;
  const files = [];
  (function walk(dir) {
    let ents; try { ents = fs.readdirSync(dir, { withFileTypes: true }); } catch (_) { return; }
    ents.sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
    for (const e of ents) {
      if (DEFAULT_SKIP_DIRS.has(e.name)) continue;
      const full = path.join(dir, e.name);
      const rel = path.relative(root, full).split(path.sep).join('/');
      if (ignored(rel)) continue;
      if (e.isDirectory()) walk(full);
      else if (e.isFile()) {
        if (SKIP_FILE.test(e.name)) continue;
        let buf; try { buf = fs.readFileSync(full); } catch (_) { continue; }
        if (buf.length > maxBytes || isBinary(buf)) continue;
        files.push({ path: rel, hash: fnv(buf), bytes: buf.length, text: buf.toString('utf8') });
      }
    }
  })(root);

  // Dedup by content hash — identical files share one body (token savings).
  const seen = new Map(); let dupTokens = 0;
  for (const f of files) { if (seen.has(f.hash)) { f.dupOf = seen.get(f.hash); dupTokens += estTokens(f.text.length); } else seen.set(f.hash, f.path); }
  const rootHash = fnv(files.map(f => f.path + ':' + f.hash).join('\n'));
  const uniqueChars = files.filter(f => !f.dupOf).reduce((n, f) => n + f.text.length, 0);
  return { root: rootHash, files, tokens: estTokens(uniqueChars), savedTokens: dupTokens, src: path.basename(root) };
}

// ── lenses (one ingest → many artifact types) ─────────────────────────────────
function tree(files) { return files.map(f => '  ' + f.path + (f.dupOf ? '  (= ' + f.dupOf + ')' : '')).join('\n'); }
function header(m, kind) {
  return `${kind} context · source: ${m.src} · root: ${m.root}\n` +
    `${m.files.length} files · ~${m.tokens.toLocaleString()} tokens` +
    (m.savedTokens ? ` · ${m.savedTokens.toLocaleString()} tokens saved by dedup` : '') +
    `\nreproducible: same repo → same root hash. generated by bfx-ingest.\n`;
}
const lensMd = (m) => `# ${m.src} — codebase context\n\n<!-- ${header(m, 'AI').replace(/\n/g, ' ')} -->\n\n## Files\n\n\`\`\`\n${tree(m.files)}\n\`\`\`\n\n` +
  m.files.filter(f => !f.dupOf).map(f => `### ${f.path}\n\n\`\`\`${fence(f.path)}\n${f.text}\n\`\`\``).join('\n\n') + '\n';
const lensXml = (m) => `<context source="${m.src}" root="${m.root}" files="${m.files.length}" tokens="${m.tokens}">\n` +
  m.files.filter(f => !f.dupOf).map(f => `  <file path="${f.path}" hash="${f.hash}"><![CDATA[\n${f.text}\n]]></file>`).join('\n') + `\n</context>\n`;
const lensJson = (m) => JSON.stringify({ source: m.src, root: m.root, tokens: m.tokens, savedTokens: m.savedTokens, files: m.files.map(f => ({ path: f.path, hash: f.hash, bytes: f.bytes, dupOf: f.dupOf || null, text: f.dupOf ? undefined : f.text })) }, null, 2);

function main(argv) {
  const a = argv.slice(2); const folder = a[0] && !a[0].startsWith('--') ? a[0] : '.';
  const get = (k, d) => { const i = a.indexOf(k); return i >= 0 ? a[i + 1] : d; };
  const format = (get('--format', 'md') || 'md').toLowerCase();
  const out = get('--out', null);
  const m = ingest(folder, { maxKb: parseInt(get('--max-kb', '256'), 10) });
  const lens = format === 'xml' ? lensXml : format === 'json' ? lensJson : lensMd;
  const body = lens(m);
  if (out) { fs.writeFileSync(out, body); }
  else process.stdout.write(body);
  process.stderr.write(`\n🦋 ${m.src}: ${m.files.length} files → ~${m.tokens.toLocaleString()} tokens` +
    (m.savedTokens ? ` (saved ${m.savedTokens.toLocaleString()} via dedup)` : '') +
    ` · root ${m.root} · format ${format}${out ? ' → ' + out : ''}\n`);
  return m;
}
if (require.main === module) main(process.argv);
module.exports = { ingest, lensMd, lensXml, lensJson };
